### ISSUE TITLE
Sorting of members of terms and definitions is not currently alphabetical; should it be?

### ISSUE THREAD

**Issue by JGoldstone** [SMPTE/st2094-50#5]
The terms and definitions in the PD of 2094-50 are not sorted alphabetically but appear to be more or less grouped functionally.

The Standards Style Guide (AG-16) has nothing explicit that I can find on the ordering of entries. But it does say that unless an exception is made, engineering documents—well, Standards, at least—should conform to "ISO/IEC Directives, Part 2 (Principles and rules for the structure and drafting of ISO and IEC documents)" at https://www.iso.org/sites/directives/current/part2/index.xhtml, except as overridden in §7 of AG-16, and I see no callout in that clause for alphabetical ordering of Terms and Definitions.

And that abovementioned ISO document says (§16.4) that "Terms and definitions should be listed according to the hierarchy of the concepts (i.e. systematic order). Alphabetical order is the least preferred order". 

Glancing at ST 2094-1, which is supposed to serve as the home of common-to-more-than-one-application terms and definitions related to the ST 2094 suite, I see that the entries are sorted alphabetically.

Maybe someone (Ellen? Raymond? Thomas?) could comment on whether there is an unspoken exception to ISO/IEC Directives, Part 2, for the ordering of Terms and Definitions. I suspect all five documents I've written (albeit all RDDs, not Engineering Documents) have sorted their Terms and Definitions alphabetically.

My preference would be alphabetical to match ST 2094-1, the common terminology reference for the suite.

**Comment by ccameron-chromium** [comment]
I originally had this as alphabetical ordering. That ordering resulted in a document that I found much harder to read.

When I found out (I think from Raymond) that alphabetical ordering was not strictly required, I switched to the current "dependency ordering", which I find makes the document much more approachable.

Unless alphabetical ordering is strictly required, I would prefer to go with the current ordering.

**Comment by ccameron-chromium** [comment]
Resolved: Conceptual order with forward references not banned

**Comment by digitaltvguy** [comment]
Hi Chris, Are you able close this issue or has SMPTE not resolved this issue?
